# Generated by Django 4.2.19 on 2025-05-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_profile_profile_picture'),
        ('forum', '0003_alter_comment_author_alter_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='forum.threadcategory'),
        ),
    ]
