# Generated by Django 4.0.4 on 2025-03-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
    ]
