# Generated by Django 4.2.16 on 2025-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Available', max_length=32),
        ),
    ]
