# Generated by Django 4.2.16 on 2025-05-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_profile_profile_picture'),
        ('merchstore', '0003_transanction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transanction',
            new_name='Transaction',
        ),
    ]
