# Generated by Django 5.1.5 on 2025-05-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_people_required_commission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-status', 'applied_on']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
